### ISSUE TITLE
android target - Lexer$TokeniserException - Lexer.java can't parse tokens following '<<' or '[[' - 

### ISSUE THREAD

**Issue by jojomickymack** [kyperbelt/YarnGdx#2]
Kudos on this fantastic library - when compiling for a desktop target, it works great! I created my own experiment, which is kind of a refactored version of the included demo.

[https://github.com/jojomickymack/yarn_dialog01](https://github.com/jojomickymack/yarn_dialog01)

When compiling for an android target, however, anything that's not a text token will throw a 'TokeniserException' when the json or yarn.txt file is getting loaded. I reduced a script to starting with

```java
<<if visited("Gravedigger") is true>>
```

(Gravedigger is the name of the node) and this is what I see

*desktop*
```
trying for the next token in line <<if visited("Gravedigger") is true>>
current_state.token_rules
5
regex \G\<\<
match?
true
rule.type
BeginCommand
line:1 col:2 text:<<
trying for the next token in line <<if visited("Gravedigger") is true>>
current_state.token_rules
8
regex \Gif(?!\w)
match?
true
rule.type
If
line:1 col:4 text:if
```
*android*
```
trying for the next token in line <<if visited("Gravedigger") is true>>
current_state.token_rules
5
regex \G\<\<
match?
true
I/System.out: rule.type
BeginCommand
line:1 col:2 text:<<
trying for the next token in line <<if visited("Gravedigger") is true>>
current_state.token_rules
8
regex \Gif(?!\w)
match?
false
```

The regex '\Gif(?!\w)' which is supposed to match the 'if' following the '<<' is not matching like it does when loading successfully on desktop. I believe that this is because of android's java 1.6 vs the desktop's java 1.8 and support for the regex '\G' flag - I see when I remove it from the 'addTransition' method, I'm able to match the if and everything else in the expression, but run into other issues.

I think this issue is fixable using a different system of parsing the line without relying on the \G (global - this means that the match is supposed to immediately follow the previous match - i.e - only when 'if' follows '<<' should this be true). 

I'll play around with it - I'd really like to see this work for android as well as desktop since this is such a cool way of handling dialog trees.

**Comment by jojomickymack** [comment]
I figured it out! In addition to using the regex as-is, which works fine for matching lines of Text, I created an additional Regex and Matcher which replaces the \G with ^ and uses a substring of the line being tokenized instead of the whole thing.
```
Regex myRegex = new Regex(rule.regex.pattern.toString().replace("\\G", "^"));
Matcher myMatch = myRegex.match(line.substring(column_number));
```
Using this new matcher works for directives inside of << and [[, but has issues matching regular lines of text - so in the block with if (rule.type == TokenType.Text), the original matcher is used, and for any other ruletype, token_text = myMatch.group();

My understanding of the actual issue is that on Android's Java 1.6, java.util.regex doesn't do what it's supposed to with the \G symbol.

Here is a [fixed version](https://github.com/jojomickymack/yarnjava/blob/master/core/src/com/kyper/yarn/Lexer.java) of the Lexer.java file - the edits are on line 289, 293, and 332.

That yarnjava repo I set up so I could pull in the fixed version of yarngdx using jitpack - that might be a good thing for you to take advantage of here btw - all you'd have to do is create a 'release' (otherwise SHAPSHOT is the only option). Jitpack makes it so you can use 'implementation 'com.github.jojomickymack:yarnjava:v1.0' in your core build.gradle file instead of using the jar or java files as described in your readme.md - it's just easier to include your library that way.

In the meantime I'm really happy I can use yarn and keep building for Android!!! Thanks!

**Comment by kyperbelt** [comment]
@jojomickymack thanks for the fix! I couldnt test on android myself but it makes sense. I put in the changes and tested that desktop target still functions :+1:  

Feel free to do pull requests as any help is greatly appreciated :) 

as for jitpack - i did try it out and it worked until i tried using it with a few other projects that had a different version of lwjgl and i wasnt able to only include the core module. Maybe I just didnt see a way of doing this but ill definitely take a look into that.

Ill close this issue for now.

**Comment by jojomickymack** [comment]
@kyperbelt 
Nice - looks like it's not 100% yet -  my fault for not highlighting this other change I'd made to get text to parse correctly - I forgot to note that additional line was changed.

[line 326 of Lexar.java](https://github.com/jojomickymack/yarnjava/blob/master/core/src/com/kyper/yarn/Lexer.java#L326)

So at 0c3c2f09a303dd77bdb2a142b4c9bf16eca67625, for android targets the lexar is parsing all non-text lines, but it chokes on text - I believe it's because previously, match.find was getting called on [this line](https://github.com/kyperbelt/YarnGdx/blob/master/core/src/com/kyper/yarn/Lexer.java#L294), and now it's not. I have to admit, I don't understand why match.find(column_number) does not work for android.

When I change match.find(column_number); to match.find(0); everything works.

Thanks for working on this - I'm not that great with regex and I know this is better left in your hands!

**Comment by jojomickymack** [comment]
it's working when I build for android now - thanks!
