### ISSUE TITLE
integer is marked as unused

### ISSUE THREAD

**Issue by arnemileswinter** [kyperbelt/YarnGdx#6]
https://github.com/kyperbelt/YarnGdx/blob/0c3c2f09a303dd77bdb2a142b4c9bf16eca67625/core/src/com/kyper/yarn/Loader.java#L111

One way to tackle this would be to try{...} catch{...} outside the for loop rather than inside of it - declaring the incrementing variable inside the try block.

We need the info in catch to properly log debugs, so my idea is that a reference of the last investigated node should be stored in the method scope

**Comment by kyperbelt** [comment]
Loader.java no longer exists.

**Comment by kyperbelt** [comment]
Loader.java no longer exists.
